
LessonPlan.create!({
  id: 12,
  lecturer: 137,
  intake_id: 10,
  student_qty: nil,
  semester: 2,
  topic: 375,
  lecture_title: nil,
  lecture_date: nil,
  start_time: nil,
  end_time: nil,
  reference: "",
  is_submitted: false,
  submitted_on: nil,
  hod_approved: nil,
  hod_approved_on: nil,
  hod_rejected: nil,
  hod_rejected_on: nil,
  data_file_name: nil,
  data_content_type: nil,
  data_file_size: nil,
  data_updated_ot: nil,
  prerequisites: "",
  year: 1,
  reason: nil,
  prepared_by: 137,
  endorsed_by: nil,
  condition_isgood: nil,
  condition_isnotgood: nil,
  condition_desc: nil,
  training_aids: nil,
  summary: nil,
  total_absent: nil,
  report_submit: nil,
  report_submit_on: nil,
  report_endorsed: nil,
  report_endorsed_on: nil,
  report_summary: nil,
  schedule: 27,
  created_at: "2013-10-02 03:29:24",
  updated_at: "2013-10-02 03:29:24"
  })

  {id: 16,
    lecturer: 72,
    intake_id: 10,
    student_qty: 30,
    semester: 1,
    topic: 230,
    lecture_title: nil,
    lecture_date: "2014-04-05",
    start_time: "2000-01-01 10:00:00",
    end_time: "2000-01-01 12:00:00",
    reference: "",
    is_submitted: true,
    submitted_on: "2014-04-30",
    hod_approved: nil,
    hod_approved_on: nil,
    hod_rejected: nil,
    hod_rejected_on: nil,
    data_file_name: "Screen Shot 2014-04-30 at 11.58.36 AM.png",
    data_content_type: "image/png",
    data_file_size: 5252,
    data_updated_ot: nil,
    prerequisites: "",
    year: 1,
    reason: nil,
    prepared_by: 72,
    endorsed_by: 72,
    condition_isgood: nil,
    condition_isnotgood: nil,
    condition_desc: nil,
    training_aids: nil,
    summary: nil,
    total_absent: nil,
    report_submit: nil,
    report_submit_on: nil,
    report_endorsed: nil,
    report_endorsed_on: nil,
    report_summary: nil,
    schedule: 42,
    created_at: "2014-04-30 03:58:48",
    updated_at: "2014-04-30 03:58:48"},
