class Kumpulan_etnikPdf < Prawn::Document
  def initialize(student, view, programme_id, students_6intakes_ids, valid)
    super({top_margin: 15,bottom_margin: 10,left_margin: 10, page_size: 'A4', page_layout: :landscape })
    @student = student
    @programme_id = programme_id
    @students_6intakes_ids = students_6intakes_ids
    @valid = valid
    @view = view
    font "Times-Roman"
    image "#{Rails.root}/app/assets/images/logo_kerajaan.png", :position => :center, :scale => 0.45
    move_down 5
    text "BAHAGIAN PENGURUSAN LATIHAN", :align => :center, :size => 11, :style => :bold
    text "KEMENTERIAN KESIHATAN MALAYSIA", :align => :center, :size => 11, :style => :bold
    move_down 5
    text "MAKLUMAT KUMPULAN ETNIK PELATIH DI INSTITUSI LATIHAN KEMENTERIAN KESIHATAN MALAYSIA", :align => :center, :size => 11, :style => :italic
    move_down 5
    if Date.today.month < 7
    text "INSTITUSI LATIHAN : KOLEJ SAINS KESIHATAN BERSEKUTU JOHOR BAHRU                                                                      **SESI:JAN-JUN #{Date.today.year}  JUL-DIS.......", :align => :left, :size => 11, :style => :bold
    else
    text "INSTITUSI LATIHAN : KOLEJ SAINS KESIHATAN BERSEKUTU JOHOR BAHRU                                                                      **SESI:JAN-JUN......  JUL-DIS #{Date.today.year}", :align => :left, :size => 11, :style => :bold
    end
    move_down 5
    kumpulan_tajuk
    kumpulan_data
    cop
   
  end
  
  
  def kumpulan_tajuk
    
    data = [["", "", "", "KUMPULAN ETNIK",""]]
    
    table(data, :column_widths => [75, 45, 34, 624, ], :cell_style => { :size => 8, :inline_format => :true}) do
      columns(3).align = :center
      row(0).background_color = 'FFE34D'
      row(0).column(0).borders = [:left, :right, :top]
      row(0).column(1).borders = [:left, :right, :top]
      row(0).column(2).borders = [:left, :right, :top]
      row(0).column(4).borders = [:left, :right, :top]
      self.width = 820
    end
  end
  
  def kumpulan_data
    
    data = [["JENIS PROGRAM/ KURSUS","KUMP","Jantina", "Melayu","Cina","India","Org Asli","Bajau","Murut","Brunei","Bisaya","Kadazan","Suluk","Kedayan","Iban","Kadazan Dusun","Sungai","Siam","Malanau","Bugis","Bidayuh","Momogun Rungus","Dusun","Lain-lain","JUMLAH"],
            [{content: "#{Programme.find(@programme_id).programme_list}", rowspan: 12},"T1SI","P","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 1, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 1, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 1, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 1, 1,@programme_id).count}"],
            ["T1SII","P","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 1, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 1, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 1, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 1, 1,@programme_id).count}"],
            ["T2SI","P","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 2, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 2, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 2, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 2, 1,@programme_id).count}"],
            ["T2SII","P","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 2, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 2, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 2, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 2, 1,@programme_id).count}"],
            ["T3SI","P","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 3, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 3, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(1, 3, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(1, 3, 1,@programme_id).count}"],
            ["T3SII","P","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 3, 2,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 3, 2,@programme_id).count}"],
            ["","L","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 1).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 2).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 3).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 4).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 5).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 6).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 7).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 8).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 9).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 10).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 11).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 12).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 13).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 14).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 15).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 16).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 17).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 18).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 19).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 20).count}","#{Student.get_student_by_intake_gender_race(2, 3, 1,@programme_id, 21).count}","#{Student.get_student_by_intake_gender(2, 3, 1,@programme_id).count}"],
            ["","JUMLAH"," ","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 1,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 2,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 3,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 4,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 5,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 6,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 7,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 8,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 9,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 10,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 11,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 12,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 13,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 14,@students_6intakes_ids).count}",
              "#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 15,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 16,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 17,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 18,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 19,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 20,@students_6intakes_ids).count}","#{@total_by_race=Student.where('course_id=? AND race2=? AND id IN (?)', @programme_id, 21,@students_6intakes_ids).count}","#{@valid.count}"]]
            
            table(data, :column_widths => [75, 45, 34, 34, 25, 27,25,30,30,32,32,32,28,38,25,38,32,28,30,28,25,35,25,25], :cell_style => { :size => 8}) do
              a = 1
              b = 13
              columns(0).align = :center
              row(0).background_color = 'FFE34D'
              row(0).column(0).borders = [:left, :right, :bottom]
              row(0).column(1).borders = [:left, :right, :bottom]
              row(0).column(2).borders = [:left, :right, :bottom]
              row(0).column(24).borders = [:left, :right, :bottom]
              while a < b do
              row(a).column(0).borders = [:left, :right]
              a += 1
            end
              self.width = 820
            end
end

def cop
  move_down 10
  text "* P - Perempuan", :align => :left, :size => 11, :indent_paragraphs => 30
  text "* L - Lelaki", :align => :left, :size => 11, :indent_paragraphs => 30
  
  text "Disediakan oleh :                                                                            Disahkan oleh : ", :align => :left, :size => 11, :indent_paragraphs => 40
  move_down 25
  text "---------------------------                                                                  -----------------------------", :align => :left, :size => 11, :indent_paragraphs => 30
  text "Nama :                                                                                                 Pengarah", :align => :left, :size => 11, :indent_paragraphs => 30
  text "Jawatan", :align => :left, :size => 11, :indent_paragraphs => 30
  
  text "Catatan : ", :align => :left, :size => 11, :indent_paragraphs => 30
  text "* Laporan setiap 6 bulan pada 15 Februari & 15 Ogos", :align => :left, :size => 11, :indent_paragraphs => 30
  
  
end
end