# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts "Seeding Roles"
RoleList = [
  "User", "Administration", "Student", "Administration Staff", "Librarian", "Staff", "Warden", "Training Administration",
  "Training Manager", "Asset Administrator", "Student Counsellor", "Facilities Administrator", "Lecturer", "Student Administrator",
  "Staff Administrator", "E-Filing", "Guest", "Programme Manager", "Disciplinary Officer", "Finance Unit", "Coordinator"
]

puts "Creating Roles"
RoleList.each do | r |
  Role.create!({name: r})
end

puts "Creating Banks"
Bank.create!([
  {id: 63, short_name: "Biro Angkasa", long_name: "Biro Angkasa", active: true},
  {id: 1, short_name: "Abrar Discounts Berhad", long_name: "Abrar Discounts Berhad", active: true},
  {id: 3, short_name: "Affin Bank Berhad", long_name: "Affin Bank Berhad", active: true},
  {id: 2, short_name: "Affin Investment Bank Berhad (Affin Merchant Bank Berhad)", long_name: "Affin Investment Bank Berhad (Affin Merchant Bank Berhad)", active: true},
  {id: 4, short_name: "Affin Islamic Bank Berhad", long_name: "Affin Islamic Bank Berhad", active: true},
  {id: 5, short_name: "Agrobank Berhad", long_name: "Agrobank Berhad", active: true},
  {id: 6, short_name: "Al Rajhi Banking & Investment Corporation (M) Berhad", long_name: "Al Rajhi Banking & Investment Corporation (M) Berhad", active: true},
  {id: 7, short_name: "Alliance Bank Malaysia Berhad", long_name: "Alliance Bank Malaysia Berhad", active: true},
  {id: 8, short_name: "Alliance Finance Berhad", long_name: "Alliance Finance Berhad", active: true},
  {id: 9, short_name: "Alliance Investment Bank Berhad(Alliance Merchant)", long_name: "Alliance Investment Bank Berhad(Alliance Merchant)", active: true},
  {id: 10, short_name: "Alliance Islamic Bank", long_name: "Alliance Islamic Bank",  active: true},
  {id: 11, short_name: "Am Islamic Bank Berhad", long_name: "Am Islamic Bank Berhad", active: true},
  {id: 13, short_name: "AmFinance Berhad", long_name: "AmFinance Berhad", active: true},
  {id: 12, short_name: "AmBank Berhad", long_name: "AmBank Berhad",  active: true},
  {id: 14, short_name: "AmInvestment Bank Berhad", long_name: "AmInvestment Bank Berhad", active: true},
  {id: 15, short_name: "Arab-Malaysian Merchant Bank Berhad", long_name: "Arab-Malaysian Merchant Bank Berhad", active: true},
  {id: 16, short_name: "Aseambankers Malaysia Berhad", long_name: "Aseambankers Malaysia Berhad", active: true},
  {id: 17, short_name: "Asia Commercial Finance(M)Berhad", long_name: "Asia Commercial Finance(M)Berhad", active: true},
  {id: 18, short_name: "Asian Finance Bank Berhad", long_name: "Asian Finance Bank Berhad", active: true},
  {id: 19, short_name: "Bangkok Bank Berhad", long_name: "Bangkok Bank Berhad",  active: true},
  {id: 20, short_name: "Bank Islam Malaysia Berhad", long_name: "Bank Islam Malaysia Berhad", active: true},
  {id: 21, short_name: "Bank Kerjasama Rakyat(M)Berhad", long_name: "Bank Kerjasama Rakyat(M)Berhad", active: true},
  {id: 22, short_name: "Bank Muamalat Malaysia Berhad", long_name: "Bank Muamalat Malaysia Berhad", active: true},
  {id: 23, short_name: "Bank Negara Malaysia", long_name: "Bank Negara Malaysia", active: true},
  {id: 24, short_name: "Bank of America Malaysia Berhad", long_name: "Bank of America Malaysia Berhad", active: true},
  {id: 25, short_name: "Bank of China (Malaysia) Berhad", long_name: "Bank of China (Malaysia) Berhad", active: true},
  {id: 26, short_name: "Bank Of Tokyo-Mitsubisi", long_name: "Bank Of Tokyo-Mitsubisi", active: true},
  {id: 27, short_name: "Bank Pembangunan(M)Berhad", long_name: "Bank Pembangunan(M)Berhad",  active: true},
  {id: 29, short_name: "Bank Persatuan Kerjasama", long_name: "Bank Persatuan Kerjasama", active: true},
  {id: 30, short_name: "Bank Pertanian Malaysia", long_name: "Bank Pertanian Malaysia", active: true},
  {id: 31, short_name: "Maybank Islamic Berhad", long_name: "Maybank Islamic Berhad", active: true},
  {id: 32, short_name: "MBF Finance Berhad", long_name: "MBF Finance Berhad", active: true},
  {id: 33, short_name: "MIDF Amanah Investment Bank Berhad", long_name: "MIDF Amanah Investment Bank Berhad", active: true},
  {id: 34, short_name: "MIMB Investment Bank Berhad(MIMB)", long_name: "MIMB Investment Bank Berhad(MIMB)", active: true},
  {id: 35, short_name: "OCBC Bank(Malaysia)Berhad", long_name: "OCBC Bank(Malaysia)Berhad", active: true},
  {id: 36, short_name: "OCBC Islamic Bank(Malaysia)Berhad", long_name: "OCBC Islamic Bank(Malaysia)Berhad", active: true},
  {id: 37, short_name: "OSK Investment Bank Berhad", long_name: "OSK Investment Bank Berhad", active: true},
  {id: 38, short_name: "Overseas Union Bank(Malaysia)Berhad", long_name: "Overseas Union Bank(Malaysia)Berhad", active: true},
  {id: 39, short_name: "Pencen", long_name: "Pencen", active: true},
  {id: 40, short_name: "Perdana Merchant Bank Berhad", long_name: "Perdana Merchant Bank Berhad", active: true},
  {id: 41, short_name: "Public Bank Berhad", long_name: "Public Bank Berhad", active: true},
  {id: 42, short_name: "Public Finance Berhad", long_name: "Public Finance Berhad", active: true},
  {id: 43, short_name: "Public Investment Bank Berhad(Public Merchant)", long_name: "Public Investment Bank Berhad(Public Merchant)", active: true},
  {id: 44, short_name: "RHB Bank Berhad", long_name: "RHB Bank Berhad", active: true},
  {id: 45, short_name: "RHB Delta Finance Berhad", long_name: "RHB Delta Finance Berhad", active: true},
  {id: 46, short_name: "RHB Islamic Bank Berhad", long_name: "RHB Islamic Bank Berhad", active: true},
  {id: 47, short_name: "RHB Sakura Merchant Bankers Berhad", long_name: "RHB Sakura Merchant Bankers Berhad", active: true},
  {id: 48, short_name: "Sabah Credit Corporation Berhad", long_name: "Sabah Credit Corporation Berhad", active: true},
  {id: 49, short_name: "Sabah Development Bank Berhad", long_name: "Sabah Development Bank Berhad", active: true},
  {id: 50, short_name: "Social Security Organization", long_name: "Social Security Organization", active: true},
  {id: 51, short_name: "Southern Bank Berhad", long_name: "Southern Bank Berhad",  active: true},
  {id: 52, short_name: "Standard Chartered Bank Malaysia Berhad", long_name: "Standard Chartered Bank Malaysia Berhad", active: true},
  {id: 53, short_name: "Tabung Haji", long_name: "Tabung Haji", active: true},
  {id: 54, short_name: "The Bank Of Nova Scotia Berhad", long_name: "The Bank Of Nova Scotia Berhad", active: true},
  {id: 55, short_name: "The Royal Bank of Scotland Berhad(ABN AMRO Bank)", long_name: "The Royal Bank of Scotland Berhad(ABN AMRO Bank)", active: true},
  {id: 56, short_name: "Tiada Maklumat", long_name: "Tiada Maklumat", active: true},
  {id: 57, short_name: "United Merchant Finance Berhad", long_name: "United Merchant Finance Berhad", active: true},
  {id: 58, short_name: "United Overseas Bank(Malaysia)Bhd", long_name: "United Overseas Bank(Malaysia)Bhd",  active: true},
  {id: 60, short_name: "Bank Rakyat", long_name: "Bank Rakyat", active: true},
  {id: 61, short_name: "Bank Simpanan Nasional", long_name: "Bank Simpanan Nasional", active: true},
  {id: 62, short_name: "Bank Utama(Malaysia)Berhad", long_name: "Bank Utama(Malaysia)Berhad", active: true},
  {id: 64, short_name: "Cagamas Berhad", long_name: "Cagamas Berhad", active: true},
  {id: 65, short_name: "CIMB Bank Berhad", long_name: "CIMB Bank Berhad", active: true},
  {id: 66, short_name: "CIMB Investment Bank Berhad", long_name: "CIMB Investment Bank Berhad", active: true},
  {id: 67, short_name: "CIMB Islamic Bank Berhad", long_name: "CIMB Islamic Bank Berhad", active: true},
  {id: 68, short_name: "Citibank Berhad", long_name: "Citibank Berhad", active: true},
  {id: 69, short_name: "Deutsche Bank(Malaysia)Sdn Bhd", long_name: "Deutsche Bank(Malaysia)Sdn Bhd", active: true},
  {id: 70, short_name: "ECM Libra Investment Bank Berhad", long_name: "ECM Libra Investment Bank Berhad", active: true},
  {id: 71, short_name: "EON Bank Berhad", long_name: "EON Bank Berhad", active: true},
  {id: 72, short_name: "EON Finance Berhad", long_name: "EON Finance Berhad",  active: true},
  {id: 73, short_name: "EONCAP Islamic Bank Berhad", long_name: "EONCAP Islamic Bank Berhad",  active: true},
  {id: 74, short_name: "GEPF", long_name: "GEPF",  active: true},
  {id: 75, short_name: "Hong Leong Bank Berhad", long_name: "Hong Leong Bank Berhad", active: true},
  {id: 76, short_name: "Hong Leong Finance Berhad", long_name: "Hong Leong Finance Berhad", active: true},
  {id: 77, short_name: "Hong Leong Islamic Bank Berhad", long_name: "Hong Leong Islamic Bank Berhad", active: true},
  {id: 78, short_name: "Hongkong Bank Bhd", long_name: "Hongkong Bank Bhd", active: true},
  {id: 79, short_name: "HSBC Amanah Malaysia Berhad(Islamic)", long_name: "HSBC Amanah Malaysia Berhad(Islamic)", active: true},
  {id: 80, short_name: "HSBC Bank Malaysia Berhad", long_name: "HSBC Bank Malaysia Berhad", active: true},
  {id: 81, short_name: "Hwang-DBS Investment Bank Berhad", long_name: "Hwang-DBS Investment Bank Berhad", active: true},
  {id: 82, short_name: "J.P Mogan Chase Bank Berhad(Chase Manhattan)", long_name: "J.P Mogan Chase Bank Berhad(Chase Manhattan)", active: true},
  {id: 83, short_name: "KAF Investment Bank Berhad", long_name: "KAF Investment Bank Berhad", active: true},
  {id: 84, short_name: "Kenanga Investment Bank Berhad", long_name: "Kenanga Investment Bank Berhad", active: true},
  {id: 85, short_name: "Kewangan Bersatu Berhad", long_name: "Kewangan Bersatu Berhad", active: true},
  {id: 86, short_name: "Kumpulan Finance House(Malaysia)Berhad", long_name: "Kumpulan Finance House(Malaysia)Berhad", active: true},
  {id: 87, short_name: "Lain-Lain", long_name: "Lain-Lain", active: true},
  {id: 88, short_name: "Lain-Lain Akaun Badan Berkanun", long_name: "Lain-Lain Akaun Badan Berkanun", active: true},
  {id: 89, short_name: "Lain-Lain Akaun Badan Bukan Berkanun", long_name: "Lain-Lain Akaun Badan Bukan Berkanun",  active: true},
  {id: 90, short_name: "Lain-Lain Bank Islam", long_name: "Lain-Lain Bank Islam",  active: true},
  {id: 91, short_name: "Lain-Lain Bank Komersial", long_name: "Lain-Lain Bank Komersial", active: true},
  {id: 92, short_name: "Lain-Lain Bank Perdagangan", long_name: "Lain-Lain Bank Perdagangan", active: true},
  {id: 93, short_name: "Lain-Lain Syarikat Kewangan", long_name: "Lain-Lain Syarikat Kewangan", active: true},
  {id: 94, short_name: "Lembaga Hasil Dalam Negeri", long_name: "Lembaga Hasil Dalam Negeri", active: true},
  {id: 95, short_name: "Malayan Banking Berhad", long_name: "Malayan Banking Berhad",  active: true},
  {id: 96, short_name: "Maybank Finance Berhad", long_name: "Maybank Finance Berhad",  active: true},
  {id: 102, short_name: "OCBC Islamic Bank(Malaysia) Berhad", long_name: "OCBC Islamic Bank(Malaysia) Berhad", active: true},
  {id: 110, short_name: "Public Islamic Bank Berhad", long_name: "Public Islamic Bank Berhad",  active: true}
])

puts "Creating Employee Grades"
Employgrade.create!([
  {id: 1, name: "N41",    group_id: 1},
  {id: 2, name: "N44",    group_id: 1},
  {id: 3, name: "N48",    group_id: 1},
  {id: 4, name: "N52",    group_id: 1},
  {id: 5, name: "N54",    group_id: 1},
  {id: 6, name: "N27",    group_id: 2},
  {id: 7, name: "N32",    group_id: 2},
  {id: 8, name: "N36",    group_id: 2},
  {id: 9, name: "N19",    group_id: 2},
  {id: 10, name: "N22",   group_id: 2},
  {id: 11, name: "N26",   group_id: 2},
  {id: 12, name: "N17",   group_id: 2},
  {id: 13, name: "N20",   group_id: 2},
  {id: 14, name: "N11",   group_id: 2},
  {id: 15, name: "N14",   group_id: 2},
  {id: 16, name: "N 3",   group_id: 2},
  {id: 17, name: "N 4",   group_id: 2},
  {id: 18, name: "N 1",   group_id: 2},
  {id: 19, name: "U41",   group_id: 1},
  {id: 20, name: "U43/44", group_id: 1},
  {id: 21, name: "U47/48", group_id: 1},
  {id: 22, name: "U51/52", group_id: 1},
  {id: 23, name: "U53/54", group_id: 1},
  {id: 24, name: "U44",   group_id: 1},
  {id: 25, name: "U48",   group_id: 1},
  {id: 26, name: "U52",   group_id: 1},
  {id: 27, name: "U54",   group_id: 1},
  {id: 28, name: "U29",   group_id: 4},
  {id: 29, name: "U32",   group_id: 4},
  {id: 30, name: "U36",   group_id: 4},
  {id: 31, name: "U41/42", group_id: 4},
  {id: 32, name: "U44",   group_id: 4},
  {id: 33, name: "U48",   group_id: 4},
  {id: 34, name: "U29",   group_id: 2},
  {id: 35, name: "U32",   group_id: 2},
  {id: 36, name: "U36",   group_id: 2},
  {id: 37, name: "U38",   group_id: 2},
  {id: 38, name: "U40",   group_id: 2},
  {id: 39, name: "U19",   group_id: 2},
  {id: 40, name: "U24",   group_id: 2},
  {id: 41, name: "U26",   group_id: 2},
  {id: 42, name: "U17",   group_id: 2},
  {id: 43, name: "U22",   group_id: 2},
  {id: 44, name: "U11",   group_id: 2},
  {id: 45, name: "U14",   group_id: 2},
  {id: 46, name: "U 3",   group_id: 2},
  {id: 47, name: "U12",   group_id: 2},
  {id: 48, name: "W41",   group_id: 1},
  {id: 49, name: "W44",   group_id: 1},
  {id: 50, name: "W48",   group_id: 1},
  {id: 51, name: "W52",   group_id: 1},
  {id: 52, name: "W54",   group_id: 1},
  {id: 53, name: "W27",   group_id: 2},
  {id: 54, name: "W32",   group_id: 2},
  {id: 55, name: "W36",   group_id: 2},
  {id: 56, name: "W17",   group_id: 2},
  {id: 57, name: "W22",   group_id: 2},
  {id: 58, name: "W26",   group_id: 2},
  {id: 59, name: "F41",   group_id: 1},
  {id: 60, name: "F44",   group_id: 1},
  {id: 61, name: "F48",   group_id: 1},
  {id: 62, name: "F52",   group_id: 1},
  {id: 63, name: "F54",   group_id: 1},
  {id: 64, name: "F29",   group_id: 2},
  {id: 65, name: "F32",   group_id: 2},
  {id: 66, name: "F38",   group_id: 2},
  {id: 67, name: "FT17",  group_id: 2},
  {id: 68, name: "FT22",  group_id: 2},
  {id: 69, name: "FT26",  group_id: 2},
  {id: 70, name: "F11",   group_id: 2},
  {id: 71, name: "F14",   group_id: 2},
  {id: 72, name: "R1",    group_id: 2},
  {id: 73, name: "R3",    group_id: 2},
  {id: 74, name: "R6",    group_id: 2},
  {id: 75, name: "M48",   group_id: 1},
  {id: 76, name: "S41",   group_id: 1},
  {id: 77, name: "S27",   group_id: 2},
  {id: 78, name: "J29",   group_id: 2},
  {id: 79, name: "S17",   group_id: 2},
  {id: 80, name: "J17",   group_id: 2},
  {id: 81, name: "KP17",  group_id: 2},
  {id: 82, name: "M52/U52", group_id: 4},
  {id: 83, name: "R17",   group_id: 2}
])


puts "Creating Holiday Calander"
((Date.today.year-8).. Date.today.year).each do | y |
  Holiday.create!([
    {hname: "Thn Baru Cina #{y}", hdate: "#{y}-01-23"},
    {hname: "Thn Baru Cina #{y}", hdate: "#{y}-01-24"},
    {hname: "Maulidul Rasul #{y}", hdate: "#{y}-02-06"},
    {hname: "Thaipusam #{y}",     hdate: "#{y}-02-07"},
    {hname: "Hari Pekerja #{y}",  hdate: "#{y}-05-01"},
    {hname: "Wesak #{y}",         hdate: "#{y}-05-05"},
    {hname: "Awal Ramadhan #{y}", hdate: "#{y}-07-21"},
    {hname: "Raya Puasa #{y}",    hdate: "#{y}-08-19"},
    {hname: "Hari Malaysia #{y}", hdate: "#{y}-09-16"},
    {hname: "Hari Raya Haji #{y}",hdate: "#{y}-10-26"},
    {hname: "Deepavali #{y}",     hdate: "#{y}-11-13"},
    {hname: "Awal Muharam #{y}",  hdate: "#{y}-11-15"},
    {hname: "Besday S.Johor #{y}", hdate: "#{y}-11-22"},
    {hname: "Hari Hol #{y}",      hdate: "#{y}-12-20"},
    {hname: "Hari Krismas #{y}",  hdate: "#{y}-12-25"}
  ])
end
