class CreateAverageInstructors < ActiveRecord::Migration
  def change
    create_table :average_instructors do |t|
      t.integer :programme_id
      t.integer :instructor_id
      t.date :evaluate_date
      t.string :title
      t.text :objective
      t.time :start_on
      t.time :end_on
      t.integer :delivery_type
      t.integer :pbq1
      t.integer :pbq2
      t.integer :pbq3
      t.integer :pbq4
      t.string :pbq1review
      t.string :pbq2review
      t.string :pbq3review
      t.string :pbq4review
      t.integer :pdq1
      t.integer :pdq2
      t.integer :pdq3
      t.integer :pdq4
      t.integer :pdq5
      t.string :pdq1review
      t.string :pdq2review
      t.string :pdq3review
      t.string :pdq4review
      t.string :pdq5review
      t.integer :dq1
      t.integer :dq2
      t.integer :dq3
      t.integer :dq4
      t.integer :dq5
      t.integer :dq6
      t.integer :dq7
      t.integer :dq8
      t.integer :dq9
      t.integer :dq10
      t.integer :dq11
      t.integer :dq12
      t.string :dq1review
      t.string :dq2review
      t.string :dq3review
      t.string :dq4review
      t.string :dq5review
      t.string :dq6review
      t.string :dq7review
      t.string :dq8review
      t.string :dq9reiew
      t.string :dq10review
      t.string :dq11review
      t.string :dq12review
      t.integer :uq1
      t.integer :uq2
      t.integer :uq3
      t.integer :uq4
      t.string :uq1review
      t.string :uq2review
      t.string :uq3review
      t.string :uq4review
      t.integer :vq1
      t.integer :vq2
      t.integer :vq3
      t.integer :vq4
      t.integer :vq5
      t.string :vq1review
      t.string :vq2review
      t.string :vq3review
      t.string :vq4review
      t.string :vq5review
      t.integer :gttq1
      t.integer :gttq2
      t.integer :gttq3
      t.integer :gttq4
      t.integer :gttq5
      t.integer :gttq6
      t.integer :gttq7
      t.integer :gttq8
      t.integer :gttq9
      t.string :gttq1review
      t.string :gttq2review
      t.string :gttq3review
      t.string :gttq4review
      t.string :gttq5review
      t.string :gttq6review
      t.string :gttq7review
      t.string :gttq8review
      t.string :gttq9review
      t.text :review
      t.integer :evaluator_id

      t.timestamps
    end
  end
end
