require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InstructorAppraisalsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # InstructorAppraisal. As you add validations to InstructorAppraisal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstructorAppraisalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all instructor_appraisals as @instructor_appraisals" do
      instructor_appraisal = InstructorAppraisal.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:instructor_appraisals)).to eq([instructor_appraisal])
    end
  end

  describe "GET show" do
    it "assigns the requested instructor_appraisal as @instructor_appraisal" do
      instructor_appraisal = InstructorAppraisal.create! valid_attributes
      get :show, {:id => instructor_appraisal.to_param}, valid_session
      expect(assigns(:instructor_appraisal)).to eq(instructor_appraisal)
    end
  end

  describe "GET new" do
    it "assigns a new instructor_appraisal as @instructor_appraisal" do
      get :new, {}, valid_session
      expect(assigns(:instructor_appraisal)).to be_a_new(InstructorAppraisal)
    end
  end

  describe "GET edit" do
    it "assigns the requested instructor_appraisal as @instructor_appraisal" do
      instructor_appraisal = InstructorAppraisal.create! valid_attributes
      get :edit, {:id => instructor_appraisal.to_param}, valid_session
      expect(assigns(:instructor_appraisal)).to eq(instructor_appraisal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstructorAppraisal" do
        expect {
          post :create, {:instructor_appraisal => valid_attributes}, valid_session
        }.to change(InstructorAppraisal, :count).by(1)
      end

      it "assigns a newly created instructor_appraisal as @instructor_appraisal" do
        post :create, {:instructor_appraisal => valid_attributes}, valid_session
        expect(assigns(:instructor_appraisal)).to be_a(InstructorAppraisal)
        expect(assigns(:instructor_appraisal)).to be_persisted
      end

      it "redirects to the created instructor_appraisal" do
        post :create, {:instructor_appraisal => valid_attributes}, valid_session
        expect(response).to redirect_to(InstructorAppraisal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instructor_appraisal as @instructor_appraisal" do
        post :create, {:instructor_appraisal => invalid_attributes}, valid_session
        expect(assigns(:instructor_appraisal)).to be_a_new(InstructorAppraisal)
      end

      it "re-renders the 'new' template" do
        post :create, {:instructor_appraisal => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested instructor_appraisal" do
        instructor_appraisal = InstructorAppraisal.create! valid_attributes
        put :update, {:id => instructor_appraisal.to_param, :instructor_appraisal => new_attributes}, valid_session
        instructor_appraisal.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested instructor_appraisal as @instructor_appraisal" do
        instructor_appraisal = InstructorAppraisal.create! valid_attributes
        put :update, {:id => instructor_appraisal.to_param, :instructor_appraisal => valid_attributes}, valid_session
        expect(assigns(:instructor_appraisal)).to eq(instructor_appraisal)
      end

      it "redirects to the instructor_appraisal" do
        instructor_appraisal = InstructorAppraisal.create! valid_attributes
        put :update, {:id => instructor_appraisal.to_param, :instructor_appraisal => valid_attributes}, valid_session
        expect(response).to redirect_to(instructor_appraisal)
      end
    end

    describe "with invalid params" do
      it "assigns the instructor_appraisal as @instructor_appraisal" do
        instructor_appraisal = InstructorAppraisal.create! valid_attributes
        put :update, {:id => instructor_appraisal.to_param, :instructor_appraisal => invalid_attributes}, valid_session
        expect(assigns(:instructor_appraisal)).to eq(instructor_appraisal)
      end

      it "re-renders the 'edit' template" do
        instructor_appraisal = InstructorAppraisal.create! valid_attributes
        put :update, {:id => instructor_appraisal.to_param, :instructor_appraisal => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instructor_appraisal" do
      instructor_appraisal = InstructorAppraisal.create! valid_attributes
      expect {
        delete :destroy, {:id => instructor_appraisal.to_param}, valid_session
      }.to change(InstructorAppraisal, :count).by(-1)
    end

    it "redirects to the instructor_appraisals list" do
      instructor_appraisal = InstructorAppraisal.create! valid_attributes
      delete :destroy, {:id => instructor_appraisal.to_param}, valid_session
      expect(response).to redirect_to(instructor_appraisals_url)
    end
  end

end
