require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InsurancePoliciesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # InsurancePolicy. As you add validations to InsurancePolicy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsurancePoliciesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all insurance_policies as @insurance_policies" do
      insurance_policy = InsurancePolicy.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:insurance_policies)).to eq([insurance_policy])
    end
  end

  describe "GET show" do
    it "assigns the requested insurance_policy as @insurance_policy" do
      insurance_policy = InsurancePolicy.create! valid_attributes
      get :show, {:id => insurance_policy.to_param}, valid_session
      expect(assigns(:insurance_policy)).to eq(insurance_policy)
    end
  end

  describe "GET new" do
    it "assigns a new insurance_policy as @insurance_policy" do
      get :new, {}, valid_session
      expect(assigns(:insurance_policy)).to be_a_new(InsurancePolicy)
    end
  end

  describe "GET edit" do
    it "assigns the requested insurance_policy as @insurance_policy" do
      insurance_policy = InsurancePolicy.create! valid_attributes
      get :edit, {:id => insurance_policy.to_param}, valid_session
      expect(assigns(:insurance_policy)).to eq(insurance_policy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InsurancePolicy" do
        expect {
          post :create, {:insurance_policy => valid_attributes}, valid_session
        }.to change(InsurancePolicy, :count).by(1)
      end

      it "assigns a newly created insurance_policy as @insurance_policy" do
        post :create, {:insurance_policy => valid_attributes}, valid_session
        expect(assigns(:insurance_policy)).to be_a(InsurancePolicy)
        expect(assigns(:insurance_policy)).to be_persisted
      end

      it "redirects to the created insurance_policy" do
        post :create, {:insurance_policy => valid_attributes}, valid_session
        expect(response).to redirect_to(InsurancePolicy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insurance_policy as @insurance_policy" do
        post :create, {:insurance_policy => invalid_attributes}, valid_session
        expect(assigns(:insurance_policy)).to be_a_new(InsurancePolicy)
      end

      it "re-renders the 'new' template" do
        post :create, {:insurance_policy => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested insurance_policy" do
        insurance_policy = InsurancePolicy.create! valid_attributes
        put :update, {:id => insurance_policy.to_param, :insurance_policy => new_attributes}, valid_session
        insurance_policy.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested insurance_policy as @insurance_policy" do
        insurance_policy = InsurancePolicy.create! valid_attributes
        put :update, {:id => insurance_policy.to_param, :insurance_policy => valid_attributes}, valid_session
        expect(assigns(:insurance_policy)).to eq(insurance_policy)
      end

      it "redirects to the insurance_policy" do
        insurance_policy = InsurancePolicy.create! valid_attributes
        put :update, {:id => insurance_policy.to_param, :insurance_policy => valid_attributes}, valid_session
        expect(response).to redirect_to(insurance_policy)
      end
    end

    describe "with invalid params" do
      it "assigns the insurance_policy as @insurance_policy" do
        insurance_policy = InsurancePolicy.create! valid_attributes
        put :update, {:id => insurance_policy.to_param, :insurance_policy => invalid_attributes}, valid_session
        expect(assigns(:insurance_policy)).to eq(insurance_policy)
      end

      it "re-renders the 'edit' template" do
        insurance_policy = InsurancePolicy.create! valid_attributes
        put :update, {:id => insurance_policy.to_param, :insurance_policy => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insurance_policy" do
      insurance_policy = InsurancePolicy.create! valid_attributes
      expect {
        delete :destroy, {:id => insurance_policy.to_param}, valid_session
      }.to change(InsurancePolicy, :count).by(-1)
    end

    it "redirects to the insurance_policies list" do
      insurance_policy = InsurancePolicy.create! valid_attributes
      delete :destroy, {:id => insurance_policy.to_param}, valid_session
      expect(response).to redirect_to(insurance_policies_url)
    end
  end

end
